berkeley-stat222/mousestyles

setup.py

MRG: fix travis CI

---

doc/problem/path.md

First draft of project 2 description.
Please give advice.
@MengfeiJiang @pttzty

Update project 2 markdown file

---

doc/problem/dynamics.md

Add overview of project 3: dynamics.md

Overview of project 3: dynamics of AS patterns

---

doc/problem/behavior.md

#8 @jarrodmillman @peterasujan 
Description of AS and IS added.
Slides from Chris included.

Update Project 1 (Monday Lecture)

---

.travis.yml
Makefile
requirements.txt

Use pytest to do pep8 and flake checking and add to Travis build.

---

CONTRIBUTING.rst

Created CONTRIBUTING.rst similar to [permute](https://github.com/statlab/permute/blob/master/CONTRIBUTE.rst).
@aksam-ahmad, please review.

MRG: create CONTRIBUTING.rst

---

mousestyles/data/__init__.py
mousestyles/data/tests/test_data.py
requirements.txt

Converts the data into a pandas.DataFrame object for easier processing.

Initial Data Loading code

---

mousestyles/data/__init__.py

Fixed parentheses and end range in line.
@peterasujan please approve.

WIP: Fix typo in data loader

---

CONTRIBUTING.rst

See #14 ( feature branch naming convention).
Please review @aksam-ahmad, @togawa28.

MRG: change naming convention for feature branch

---

doc/develop/HOWTO_SETUP_SSH_KEY.rst

See #14.
Please review @aksam-ahmad, @togawa28.

WIP: documentation for setup SSH key

---

doc/problem/distribution.md

MRG: Update distribution

---

doc/problem/path.md

Revised the overview of the project 2 which is about the path diversity. @jarrodmillman ,@peterasujan, @shamindras please review the changes.

MRG: Revision of Project 2: Path model

---

CONTRIBUTING.rst
tools/README.md

Also, add README for tools directory.
Closes #46 and I believe #14.

MRG: Documentation of pre-commit hook and interactive rebase.

---

doc/problem/behavior.md

@peterasujan @dylandaniels - First draft
Could you please review?

MRG: Revise overview 1 "Behavioural Analysis" issue #35 and issue #8

---

CONTRIBUTING.rst
tools/README.md
tools/bash-and-git.sh

MRG: add git/bash config tips and contributing guidelines.

---

mousestyles/data/__init__.py
mousestyles/data/tests/test_data.py

#16 
Wrote load_interval and load_movement functions.
Please check.
Also, I'm not very sure how the `from mousestyle import data_dir` works. But I tried writing my path with `data_dir` joined in. If it's correct, I will just delete my original path without `data_dir` (they are commented out now).
@dylandaniels

MRG: data loader functions

---

mousestyles/__init__.py
mousestyles/as_is_demo.py
mousestyles/data_utils.py
mousestyles/hcm_data_begin_script.py
mousestyles/intervals.py
mousestyles/pca_hcm_data.py
mousestyles/strain_classification.py

I have edited the python files to make them executable in python3 .Please check it.@jarrodmillman @peterasujan @jcyhong .

MRG:I edit all the below python files to make them executable in python3

---

doc/source/report/behavior.rst

formula for the metric calculation.
This is to make it easier to present back to the Tecott lab
on 04/18/2016.
This is is for issue #99.
@dylandaniels - could you please review?

MRG: Include an example table for data requirement and also

---

mousestyles/data/__init__.py

See #117.
@changsiyao, can you help me check whether it is okay or not. Do we have to make any comment in the code? Thanks.

MRG: fix home base bug in load_movement

---

mousestyles/data/__init__.py
mousestyles/data/tests/test_data.py

This is very much WIP (no tests yet), but I thought I'd put it up if anyone has comments.
This addresses #84.

MRG: add function to merge activity intervals with movement data.

---

mousestyles/data/__init__.py
mousestyles/data/tests/test_data.py

Loads the data from the directory data/txy_coords/recordingStartTimeEndTime.

MRG: Data loader for mouse-day start and end times

---

mousestyles/path_index.py
mousestyles/tests/test_path.py

See the second task in #122. 
Please review, @alannaiverson, @aksam-ahmad, thanks.
@changsiyao, can you help me check whether I put the files correctly? Thanks.

MRG: Add path_index function

---

setup.py

@jJasonWang @alannaiverson 
Hey, I created the visualization folder, help me check if the setup is correct. We probably won't be testing these plotting functions, that's why I didn't create a test folder.
Let me know what you guys think.

MRG: Adding visualization folder setup

---

mousestyles/data/__init__.py
mousestyles/data/tests/test_data.py

MRG: add data loader that load features of each 2-hr bin

---

doc/source/report/overview.rst

please review @dylandaniels @peterasujan @shamindras @jarrodmillman

MRG: add description for issue #83

---

mousestyles/path_diversity/__init__.py
mousestyles/path_diversity/filter_path.py
mousestyles/path_diversity/tests/test_filter_path.py

See the third task in #122.
Please review, @alannaiverson, @aksam-ahmad, @jcpalumbo3, @sicihuang, @togawa28

MRG: add filter_path function

---

doc/source/Makefile
doc/source/index.rst
doc/source/report/overview.rst
doc/source/report/plots/heat_map_0_0_0.py
mousestyles/visualization/path_diversity_plotting.py

I cherry-picked these from @alannaiverson .
See #150 for additional details.

MRG: Alanna Iverson path plot

---

doc/source/report/dynamics.rst

MRG: report write-up updated

---

mousestyles/GLRT_distribution.py
mousestyles/tests/test_GLRT_distribution.py

MRG: Powerlaw Generalized Likelihood Ratio Test

---

mousestyles/dynamics/__init__.py
mousestyles/dynamics/tests/test_dynamics.py

Cherry-picking from #161
Here are my remotes before I started:
```
$ git remote -v
origin  git@github.com:jarrodmillman/mousestyles.git (fetch)
origin  git@github.com:jarrodmillman/mousestyles.git (push)
upstream        git@github.com:berkeley-stat222/mousestyles.git (fetch)
upstream        git@github.com:berkeley-stat222/mousestyles.git (push)
```
And here is what I did:
```
$ git checkout master
$ git pull upstream master
$ git remote add Chenyu-Renee git@github.com:Chenyu-Renee/mousestyles.git
$ git fetch Chenyu-Renee contributing-issue#160
$ git checkout -b Chenyu-Renee_contributing-issue#160
$ git cherry-pick 6744de5 ae544b8
$ git lg
$ git status
$ git push origin Chenyu-Renee_contributing-issue#160
```
Then I made this pull request.

Chenyu renee contributing issue#160

---

mousestyles/est_power_param.py
mousestyles/tests/test_est_power_param.py
setup.py

Cherry-picking from #148 
Here are my remotes before I started:
```
$ git remote -v
origin  git@github.com:jarrodmillman/mousestyles.git (fetch)
origin  git@github.com:jarrodmillman/mousestyles.git (push)
upstream        git@github.com:berkeley-stat222/mousestyles.git (fetch)
upstream        git@github.com:berkeley-stat222/mousestyles.git (push)
```
And here is what I did:
```
$ git checkout master
$ git pull upstream master
$ git remote add z357412526 git@github.com:z357412526/mousestyles.git
$ git fetch z357412526 powerlaw2
$ git checkout -b z357412526_powerlaw2
$ git cherry-pick 891ace2 6ba42ff 7e823a5 035eb9a 6db97ed 4a993d9 9aba59d 85aff4b 9f4c392 55c2d55 88052bb 5c75229
$ git rebase -i HEAD~12
```
I squashed your commit history, since it was mostly fixes and improvements to your …

power law estimation

---

doc/source/report/distribution.rst
doc/source/report/plots/hist_kolmogorov.py
mousestyles/distributions/kolmogorov_test.py
mousestyles/distributions/test/test_kolmogorov_test.py

1. Perform the Kolmogorov-Smirnov test on the distances travelled in 20ms by a mouse of a strain in a day
2. Create subfolder for the Powerlaw subproject.
This commit is similar to Pull Request #149 , except this one uses Kolmogorov-Smirnov test instead of Generalized Likelihood Ratio test.

MRG: Powerlaw Kolmogorov–Smirnov test

---

doc/source/report/path.rst
doc/source/report/plots/plot_path.py
mousestyles/visualization/plot_path.py

Added the function to visualize paths in the original form. For details see #170.
@jJasonWang please review.

MRG: Add function for plotting paths

---

doc/source/report/distribution.rst

We create this place to work on distribution project report together.

MRG: distribution project report.

---

mousestyles/dynamics/__init__.py
mousestyles/dynamics/tests/test_dynamics.py
setup.py

Cherry-picking from #176.
Here is what I did.
Here are my remotes:
```
$ git remote -v
origin  git@github.com:jarrodmillman/mousestyles.git (fetch)
origin  git@github.com:jarrodmillman/mousestyles.git (push)
upstream        git@github.com:berkeley-stat222/mousestyles.git (fetch)
upstream        git@github.com:berkeley-stat222/mousestyles.git (push)
```
First, I made sure my local master branch was up to date.
```
git checkout master 
git pull upstream master
```
Then
```
git remote add wyshi git@github.com:wyshi/mousestyles.git
git fetch wyshi subproject-issue#166
git checkout -b wyshi-rebase-subproject-issue#166
git cherry-pick 8acc3bf 893c1cb
git push origin wyshi-rebase-subproject-issue#166 
```
Then I made this pull request.

MRG: Wyshi rebase subproject issue#166

---

mousestyles/data/__init__.py

See https://github.com/berkeley-stat222/mousestyles/issues/107#issuecomment-217292169 for discussion.
@jarrodmillman this probably should be merged quickly, as it may impact several other groups' work. It may also warrant an announcement on Piazza.

MRG: BUG: Fix incorrect data loading due to filename inconsistency.

---

mousestyles/data/__init__.py
mousestyles/data/tests/test_data.py

WIP: add time matrix for dynamics pattern project

---

mousestyles/mww.py
mousestyles/tests/test_mww.py

Mann–Whitney–Wilcoxon (MWW) non parametric test on distances.

MRG: MWW test

---

doc/source/report/distribution.rst

MRG: Update distribution report

---

mousestyles/behavior/__init__.py
mousestyles/behavior/behavior.py
mousestyles/behavior/behavior_tree.py
mousestyles/behavior/construct_trees.py
mousestyles/behavior/metrics.py
mousestyles/behavior/tests/test_behavior.py
mousestyles/pytest.ini
requirements.txt
setup.py

MRG: Dylandaniels behavior
